- name: Ensure Redis is installed.
  apt:
    name: "{{ redis_package }}"
    state: present

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
#  notify: restart redis

- name: Restart redis
  service: "name={{ redis_daemon }} state=restarted"

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
